### ISSUE TITLE
FATAL[0000] decode config at /singbox.json: route.rules[0].action: json: unknown field "action"

### ISSUE THREAD

**Issue by universe5ht** [Anidetrix/singbox-vless-mikrotik#2]
В последней версии наблюдаю ошибку 
FATAL[0000] decode config at /singbox.json: route.rules[0].action: json: unknown field "action"

![Screenshot 2024-11-23 122500](https://github.com/user-attachments/assets/5b085b19-d1ba-4b1c-b979-7be69b361836)
![Screenshot 2024-11-23 122446](https://github.com/user-attachments/assets/61c520fc-564b-40ba-873a-171791c87258)

P.s.
Версия singbox-vless-mikrotik:v1.10.1 работает без проблем.

**Comment by Anidetrix** [comment]
Проблема произошла из за того что 1.10.2 собралась с конфигурацией под 1.11, исправил
